name: FreeRPG
version: ${project.version}
main: mc.carlton.freerpg.FreeRPG
api-version: 1.13
authors: [JackCarlton]
description: Made from Spite
commands:
  frpg:
    description: Main FreeRPG command, type /frpg help for more info
    aliases: [freeRPG]
  spite:
    descriptions: Tells you what spite is good for.

